rm ./set60/*.plt
rm ./set60/fraction.txt
rm ./set60/nohup.out
rm ./set61/*.plt
rm ./set61/fraction.txt
rm ./set61/nohup.out
rm ./set62/*.plt
rm ./set62/fraction.txt
rm ./set62/nohup.out
rm ./set63/*.plt
rm ./set63/fraction.txt
rm ./set63/nohup.out
rm ./set64/*.plt
rm ./set64/fraction.txt
rm ./set64/nohup.out
rm ./set65/*.plt
rm ./set65/fraction.txt
rm ./set65/nohup.out
rm ./set66/*.plt
rm ./set66/fraction.txt
rm ./set66/nohup.out
rm ./set67/*.plt
rm ./set67/fraction.txt
rm ./set67/nohup.out
rm ./set68/*.plt
rm ./set68/fraction.txt
rm ./set68/nohup.out
