rm ./set10/*.plt
rm ./set10/fraction.txt
rm ./set10/nohup.out
rm ./set11/*.plt
rm ./set11/fraction.txt
rm ./set11/nohup.out
rm ./set12/*.plt
rm ./set12/fraction.txt
rm ./set12/nohup.out
rm ./set16/*.plt
rm ./set16/fraction.txt
rm ./set16/nohup.out
rm ./set17/*.plt
rm ./set17/fraction.txt
rm ./set17/nohup.out
rm ./set18/*.plt
rm ./set18/fraction.txt
rm ./set18/nohup.out
rm ./set19/*.plt
rm ./set19/fraction.txt
rm ./set19/nohup.out
rm ./set22/*.plt
rm ./set22/fraction.txt
rm ./set22/nohup.out
rm ./set28/*.plt
rm ./set28/fraction.txt
rm ./set28/nohup.out
rm ./set29/*.plt
rm ./set29/fraction.txt
rm ./set29/nohup.out
rm ./set30/*.plt
rm ./set30/fraction.txt
rm ./set30/nohup.out
rm ./set34/*.plt
rm ./set34/fraction.txt
rm ./set34/nohup.out
rm ./set35/*.plt
rm ./set35/fraction.txt
rm ./set35/nohup.out
rm ./set36/*.plt
rm ./set36/fraction.txt
rm ./set36/nohup.out
rm ./set41/*.plt
rm ./set41/fraction.txt
rm ./set41/nohup.out
rm ./set42/*.plt
rm ./set42/fraction.txt
rm ./set42/nohup.out
rm ./set43/*.plt
rm ./set43/fraction.txt
rm ./set43/nohup.out
rm ./set50/*.plt
rm ./set50/fraction.txt
rm ./set50/nohup.out
rm ./set51/*.plt
rm ./set51/fraction.txt
rm ./set51/nohup.out
rm ./set52/*.plt
rm ./set52/fraction.txt
rm ./set52/nohup.out
rm ./set53/*.plt
rm ./set53/fraction.txt
rm ./set53/nohup.out
rm ./set54/*.plt
rm ./set54/fraction.txt
rm ./set54/nohup.out
rm ./set55/*.plt
rm ./set55/fraction.txt
rm ./set55/nohup.out
rm ./set56/*.plt
rm ./set56/fraction.txt
rm ./set56/nohup.out
rm ./set57/*.plt
rm ./set57/fraction.txt
rm ./set57/nohup.out
rm ./set58/*.plt
rm ./set58/fraction.txt
rm ./set58/nohup.out
rm ./set59/*.plt
rm ./set59/fraction.txt
rm ./set59/nohup.out
rm ./set8/*.plt
rm ./set8/fraction.txt
rm ./set8/nohup.out
rm ./set9/*.plt
rm ./set9/fraction.txt
rm ./set9/nohup.out
